name:                BotTelegramSlack
version:             0.1.0.0
github:              "githubuser/BotTelegramSlack"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/BotTelegramSlack#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- bytestring
- http-conduit
- conduit-extra
- conduit
- resourcet
- http-client
- http-types
- http-client-tls
- req
- unordered-containers
- vector
- mtl
- hashable
- delay
library:
  source-dirs: src

executables:
  BotTelegramSlack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BotTelegramSlack

tests:
  BotTelegramSlack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BotTelegramSlack
    - tasty
    - tasty-hunit
    - transformers
    - scientific
